CREATE DEFINER=`root`@`localhost` PROCEDURE `registerEmployee`(
     IN p_address VARCHAR(255),
    IN p_applicant_name VARCHAR(255),
    IN p_cgpa varchar(20),
    IN p_city VARCHAR(255),
    IN p_cnic VARCHAR(255),
    IN p_degree VARCHAR(255),
    IN p_dep_id INT,
    IN p_dob DATE,
    IN p_email VARCHAR(255),
    IN p_emp_id INT,
    IN p_gender VARCHAR(10),
    IN p_github_profile_url VARCHAR(255),
    IN p_hire_date DATE,
    IN p_job_id INT,
    IN p_linkedin_profile_url VARCHAR(255),
    IN p_major VARCHAR(255),
    IN p_phone_number VARCHAR(255),
    IN p_role_id INT,
    IN p_salary int,
    IN p_university VARCHAR(255),
    IN p_zipcode VARCHAR(255)
)
BEGIN
    INSERT INTO employee (
          address,
        name,
        cgpa,
        city,
        cnic,
        degree,
        dep_id,
        dob,
        email,
        emp_id,
        gender,
        github_profile_url,
        hire_date,
        job_id,
        linkedin_profile_url,
        major,
        phone_number,
        role_id,
        salary,
        university,
        zipcode
    ) 
    VALUES (
         p_address,
        p_applicant_name,
        p_cgpa,
        p_city,
        p_cnic,
        p_degree,
        p_dep_id,
        p_dob,
        p_email,
        p_emp_id,
        p_gender,
        p_github_profile_url,
        p_hire_date,
        p_job_id,
        p_linkedin_profile_url,
        p_major,
        p_phone_number,
        p_role_id,
        p_salary,
        p_university,
        p_zipcode
    );
    
    DELETE FROM applications WHERE application_id = p_emp_id;
END